import { createApp } from 'vue'
import { createPinia } from 'pinia'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import '@fontsource-variable/inter'
import './style.css'
import './mobile.css'
import './font.css'
import App from './App.vue'
import router from './router.ts'
createApp(App).use(createPinia()).use(router).use(ElementPlus).mount('#app')
