package com.samlong.controller;
import com.samlong.model.Product;import com.samlong.repository.ProductRepository;import com.samlong.service.AuditLogService;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.security.authentication.AnonymousAuthenticationToken;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import javax.persistence.criteria.Predicate;import javax.validation.Valid;import java.util.*;
@RestController @RequestMapping("/api/products") public class ProductController{
 private final ProductRepository repo;private final AuditLogService audit;public ProductController(ProductRepository r,AuditLogService a){repo=r;audit=a;}
 @GetMapping public Object all(Authentication auth,@RequestParam(required=false) Integer page,@RequestParam(defaultValue="10") Integer size,@RequestParam(required=false) String keyword,@RequestParam(required=false) String status){if(isAdmin(auth)&&page!=null){Specification<Product> spec=(root,query,cb)->{List<Predicate> p=new ArrayList<Predicate>();if(hasText(keyword)){String value="%"+keyword.trim().toLowerCase()+"%";p.add(cb.or(cb.like(cb.lower(root.<String>get("title")),value),cb.like(cb.lower(root.<String>get("content")),value)));}if(hasText(status))p.add(cb.equal(root.get("status"),status));return cb.and(p.toArray(new Predicate[0]));};return repo.findAll(spec,PageRequest.of(Math.max(0,page),safeSize(size),Sort.by("sortOrder").ascending().and(Sort.by("id").ascending())));}return isAdmin(auth)?repo.findAll(Sort.by("sortOrder").ascending().and(Sort.by("id"))):repo.findByStatusOrderBySortOrderAscIdAsc("ACTIVE");}
 @GetMapping("/{id}")public Product one(@PathVariable Long id,Authentication auth){Product v=repo.findById(id).orElseThrow(()->new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND));if(!isAdmin(auth)&&!"ACTIVE".equals(v.getStatus()))throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND);return v;}
 private boolean isAdmin(Authentication auth){return auth!=null&&auth.isAuthenticated()&&!(auth instanceof AnonymousAuthenticationToken);}private boolean hasText(String v){return v!=null&&!v.trim().isEmpty();}private int safeSize(Integer size){return Math.min(100,Math.max(1,size==null?10:size));}
 @PostMapping public Product create(@Valid @RequestBody Product v){v.setId(null);Product saved=repo.save(v);audit.record("CREATE","PRODUCT",saved.getId(),saved.getTitle());return saved;}@PutMapping("/{id}")public Product update(@PathVariable Long id,@Valid @RequestBody Product v){v.setId(id);Product saved=repo.save(v);audit.record("UPDATE","PRODUCT",saved.getId(),saved.getTitle());return saved;}@DeleteMapping("/{id}")public void delete(@PathVariable Long id){Product v=repo.findById(id).orElseThrow(()->new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND));repo.delete(v);audit.record("DELETE","PRODUCT",id,v.getTitle());}
}
