<script setup lang="ts">
type Color={colorName:string;hexCode:string}
type Product={id:number;title:string;content?:string;highlights?:string;price?:number;imageUrl:string;imageUrls?:string[];colors?:Color[];badge?:string;rangeText?:string;powerText?:string;speedText?:string;batteryText?:string;chargeTimeText?:string;warrantyText?:string;weightText?:string}
const route=useRoute();const config=useRuntimeConfig();const contentApi=import.meta.server?config.apiServer:config.public.apiBase
const {data:product,error}=await useFetch<Product>(`${contentApi}/products/${route.params.id}`,{key:`product-${route.params.id}`})
if(error.value||!product.value)throw createError({statusCode:404,statusMessage:'Không tìm thấy sản phẩm'})
const primaryImage=computed(()=>product.value?.id===1?'/images/campaign/hero-red-v1.png':product.value?.id===2?'/images/campaign/hero-green-v1.png':product.value?.imageUrl)
const gallery=computed(()=>Array.from(new Set([primaryImage.value,...(product.value?.imageUrls||[])].filter(Boolean) as string[])))
const selectedImage=ref(gallery.value[0]||'');const selectedColor=ref(product.value.colors?.[0]?.colorName||'')
const highlights=computed(()=>product.value?.highlights?.split('\n').map(v=>v.trim()).filter(Boolean)||[])
const specifications=computed(()=>[
  ['QUÃNG ĐƯỜNG',product.value?.rangeText],['CÔNG SUẤT',product.value?.powerText],['TỐC ĐỘ',product.value?.speedText],['PIN',product.value?.batteryText],['SẠC ĐẦY',product.value?.chargeTimeText],['TRỌNG LƯỢNG',product.value?.weightText],['BẢO HÀNH',product.value?.warrantyText]
].filter(item=>item[1]))
const money=(value?:number)=>value==null?'Liên hệ':new Intl.NumberFormat('vi-VN').format(value)+' đ'
useSeoMeta({title:()=>`${product.value?.title} | Sam.Loong`,description:()=>product.value?.content||'Xe máy điện Sam.Loong',ogImage:()=>product.value?.imageUrl})
</script>
<template><main><SiteHeader/><div class="detail-breadcrumb"><NuxtLink to="/">Trang chủ</NuxtLink><span>/</span><span>Xe máy điện</span></div><section v-if="product" class="product-detail"><div class="product-gallery"><div class="detail-image" :style="{backgroundImage:`url('${selectedImage}')`}"><span>{{product.badge||'MỚI'}}</span></div><div v-if="gallery.length>1" class="gallery-thumbs"><button v-for="url in gallery" :key="url" :class="{active:selectedImage===url}" :style="{backgroundImage:`url('${url}')`}" aria-label="Chọn ảnh sản phẩm" @click="selectedImage=url"/></div></div><div class="product-detail-copy"><p class="detail-kicker">XE MÁY ĐIỆN SAM.LOONG</p><h1>{{product.title}}</h1><strong>{{money(product.price)}}</strong><div v-if="product.colors?.length" class="product-colors"><small>MÀU SẮC: <b>{{selectedColor}}</b></small><div><button v-for="color in product.colors" :key="color.colorName" :class="{active:selectedColor===color.colorName}" :style="{backgroundColor:color.hexCode}" :title="color.colorName" @click="selectedColor=color.colorName"/></div></div><div class="detail-specs"><div v-for="spec in specifications.slice(0,3)" :key="spec[0]"><small>{{spec[0]}}</small><b>{{spec[1]}}</b></div></div><p class="detail-content">{{product.content}}</p><NuxtLink class="primary-cta" to="/#booking">ĐĂNG KÝ LÁI THỬ</NuxtLink></div></section><section v-if="product" class="product-information section"><div><p class="detail-kicker">ĐIỂM NỔI BẬT</p><h2>ĐƯỢC TẠO RA CHO<br>NHỊP SỐNG ĐÔ THỊ</h2><ul><li v-for="item in highlights" :key="item">{{item}}</li></ul></div><div class="full-specs"><div v-for="spec in specifications" :key="spec[0]"><span>{{spec[0]}}</span><b>{{spec[1]}}</b></div></div></section><section class="detail-banner"><span>TRẢI NGHIỆM SAM.LOONG</span><h2>SẴN SÀNG CHO<br>CHUYẾN ĐI MỚI?</h2><NuxtLink to="/#booking">Đặt lịch ngay</NuxtLink></section><SiteFooter/></main></template>
